name: 'Voting'
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  democracy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate vote
        uses: Xiaobei09/git-democracy@main
        with:
          configPath: .
